[build]
  base = "/"
  publish = "dist/"
  command = "npm run build" # command to build your frontend

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
