[build]
  base = "/"
  publish = "dist/"
  command = "npm install webpack-cli && npm run build"


[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
