[build]
  base = "/"
  publish = "build/" # or "dist/" or wherever your built frontend files are located
  command = "npm install && npm run build" # command to build your frontend

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
